name: linux workflow
on: workflow_dispatch
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: cmake install
      - name: make application
        run: |
          cmake -H. -Bbuild
          cmake --build build --target point
          build/point && echo
