name: windows workflow
on: workflow_dispatch
jobs:
  make:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: make application
        run: |
          cmake -H. -Bbuild
          cmake --build build --target point
          ./a.exe
