name: windows workflow
on: workflow_run
jobs:
  make:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: make application
        run: |
          cmake -Bbuild
          cmake --build build --target point
          build/.\point.exe
